default:
  image: "chapel/chapel:latest"

stages:
  - build_single_locale
  - test_single_locale
#  - build_multi_locale
#  - test_multi_locale

before_script:
  - echo "Starting CI script"

################################################################################

compile_dbg:
  stage: build_single_locale
  artifacts:
    untracked: true
  script:
    - export PATH_TO_CBLAS_DIR="/usr/include"
    - export PATH_TO_BLAS_LIBS="/usr/lib64"
    - export PATH_TO_LAPACKE_INCLUDE_DIR="/usr/include"
    - export PATH_TO_LIBGFORTRAN="/usr/lib64"
    - export PATH_TO_LAPACK_BINARIES="/usr/lib64"
    - echo "Building single locale debug version of FREI."
    - chpl -o frei_dbg
           --warnings
           --warn-unstable
           -I$PATH_TO_CBLAS_DIR
           -L$PATH_TO_BLAS_LIBS -lcblas
           -I$PATH_TO_LAPACKE_INCLUDE_DIR
           -L$PATH_TO_LIBGFORTRAN -lgfortran
           -L$PATH_TO_LAPACK_BINARIES -llapacke -llapack -lcblas
           --main-module "FREI" src/FREI.chpl
                                src/fr.chpl
                                src/temporal.chpl
                                src/output.chpl
                                src/boundary.chpl
                                src/frmesh.chpl
                                src/mapping.chpl
                                src/mesh.chpl
                                src/gmesh.chpl
                                src/riemann.chpl
                                src/flux.chpl
                                src/correction.chpl
                                src/limiter.chpl
                                src/projection.chpl
                                src/quadrature.chpl
                                src/interpolation.chpl
                                src/polynomials.chpl
                                src/sourceterm.chpl
                                src/init.chpl
                                src/ringleb.chpl
                                src/config.chpl
                                src/input.chpl
                                src/parameters.chpl
                                src/testing.chpl

compile_opt:
  stage: build_single_locale
  artifacts:
    untracked: true
  script:
    - echo "Building single locale release version of FREI."
    - chpl -o frei_opt
           --fast
           --set lapackImpl=off
           --set blasImpl=off
           --main-module "FREI" src/FREI.chpl
                                src/fr.chpl
                                src/temporal.chpl
                                src/output.chpl
                                src/boundary.chpl
                                src/frmesh.chpl
                                src/mapping.chpl
                                src/mesh.chpl
                                src/gmesh.chpl
                                src/riemann.chpl
                                src/flux.chpl
                                src/correction.chpl
                                src/limiter.chpl
                                src/projection.chpl
                                src/quadrature.chpl
                                src/interpolation.chpl
                                src/polynomials.chpl
                                src/sourceterm.chpl
                                src/init.chpl
                                src/ringleb.chpl
                                src/config.chpl
                                src/input.chpl
                                src/parameters.chpl
                                src/testing.chpl

# compile_dbg_multi_locale:
#   stage: build_multi_locale
#   image: "chapel/chapel-gasnet:latest"
#   script:
#     - chpl -o frei_dbg_multi_locale --main-module "FREI" src/FREI.chpl          \
#                                                          src/input.chpl         \
#                                                          src/config.chpl        \
#                                                          src/polynomials.chpl   \
#                                                          src/correction.chpl    \
#                                                          src/interpolation.chpl \
#                                                          src/mesh.chpl          \
#                                                          src/gmesh.chpl         \
#                                                          src/testing.chpl       \
#                                                          src/parameters.chpl

# compile_opt_multi_locale:
#   stage: build_multi_locale
#   image: "chapel/chapel-gasnet:latest"
#   script:
#     - chpl -o frei_opt_multi_locale --main-module "FREI" src/FREI.chpl          \
#                                                          src/input.chpl         \
#                                                          src/config.chpl        \
#                                                          src/polynomials.chpl   \
#                                                          src/correction.chpl    \
#                                                          src/interpolation.chpl \
#                                                          src/mesh.chpl          \
#                                                          src/gmesh.chpl         \
#                                                          src/testing.chpl       \
#                                                          src/parameters.chpl

################################################################################

run_1d_test_dbg:
  stage: test_single_locale
  needs: [compile_dbg]
  script:
    - ls
    - ./frei_dbg --inputFile=test-cases/inputTest.toml

run_1d_test_opt:
  stage: test_single_locale
  needs: [compile_opt]
  script:
    - ls
    - ./frei_opt --inputFile=test-cases/inputTest.toml

# run_1d_test_dbg_multi_locale:
#   stage: test_multi_locale
#   image: "chapel/chapel-gasnet:latest"
#   needs: [compile_dbg_multi_locale]
#   script:
#     - ./frei_dbg_multi_locale_real nl 1 --inputFile=test-cases/inputTest.toml
#     - ./frei_dbg_multi_locale_real nl 2 --inputFile=test-cases/inputTest.toml
# 
# run_1d_test_opt_multi_locale:
#   stage: test_multi_locale
#   image: "chapel/chapel-gasnet:latest"
#   needs: [compile_opt_multi_locale]
#   script:
#     - ./frei_opt_multi_locale_real nl 1 --inputFile=test-cases/inputTest.toml
#     - ./frei_opt_multi_locale_real nl 2 --inputFile=test-cases/inputTest.toml

################################################################################

