[parPhysics]
  nDims  =  2
  eqSet  =  6

[parFluid]
  fMolMass = 0.0289660
  fGamma   = 1.40
  fVisc    = 0.00001787920
  fKappa   = 0.02529920

[parMesh]
  meshFormat    = 1
  meshFile      = "../../../meshfiles/ringleb0.gmsh"

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 2
  minOrder = 2
  maxOrder = 2
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme     = 3
  timeStepMethod = 1
  timeStep       = 3.0e-2
  cfl            = 2.25e-1

[parOutput]
  ioIter  =  200
  maxIter = 2000
  ioTime  = 0.00
  maxTime = 0.00
  l2ResStop = 1.0e-15
  l2SolStop = 0.0
  outError = 62

[parRef]
  lengRef = 1.0
  velMRef = 1.0
  tempRef = 1.0
  presRef = 1.0

[parFamilies]
  nFamilies = 5

[parFamilies.1]
  familyName = "MeshInterior"
  familyDimension = 2
  familyType = 0
  familySubType = 62
  familyParameters = []

[parFamilies.2]
  familyName = "Inner"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.3]
  familyName = "Outer"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.4]
  familyName = "Inflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.5]
  familyName = "Outflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

