(* ::Package:: *)

(* ::Input:: *)
(*throatX=4/10;*)
(*throatArea=2/10;*)
(*exitArea=4/10;*)
(*nozzleArea[x_]:=25/9*(exitArea-throatArea)(x-throatX)^2+throatArea*)
(**)
(*fGamma=14/10;*)
(*aux[mach_]:=1+(fGamma-1)/2*mach^2*)
(*func[areaRatio_,mach_]:=areaRatio^2-1/mach^2*(2/(fGamma+1)*aux[mach])^((fGamma+1)/(fGamma-1))*)
(**)
(*nozzleMachSub[areaRatio_]:=machSol/.N[Solve[func[areaRatio,machSol]==0&&areaRatio>=1&&machSol<=1&&machSol>=0,machSol,Reals]][[1]]*)
(*nozzleMachSup[areaRatio_]:=machSol/.N[Solve[func[areaRatio,machSol]==0&&areaRatio>=1&&machSol>=1,machSol,Reals]][[1]]*)
(**)
(*dens[mach_]:=aux[mach]^(-1/(fGamma-1))*)
(*pres[mach_]:=aux[mach]^(-fGamma/(fGamma-1))*)
(*temp[mach_]:=aux[mach]^(-1)*)
(**)
(*For[ i=1,i<=5,i++,*)
(*mach=i/10;*)
(*Print["Mach: ",N[mach],", Density: ",N[dens[mach]],", Pressure: ", N[pres[mach]],", Temperature: ", N[temp[mach]]]*)
(*]*)
(**)
(*Plot[{nozzleArea[x]/2,*)
(*-nozzleArea[x]/2,*)
(*nozzleMachSub[nozzleArea[x]/throatArea]},*)
(*{x,0,1},PlotRange->{{0,1},{-0.2,1}},Filling->Axis,ImageSize->Full]*)
(**)
(*machPS[x_] :=((1+0.2*x^2)/(1.4*x^2-0.2))^0.5*)
(*Plot[machPS[x],{x,1,2.2}]*)
(*Plot[machPS[x],{x,1,100}]*)
(*Plot[machPS[x],{x,1,1000}]*)
(*Plot[machPS[x],{x,1,1000000}]*)
(*Limit[machPS[x],x->\[Infinity]]*)
(*machPS[2.1972]*)
(*machPS[2.1972]*1.84*)



