[parPhysics]
  nDims  =  2
  eqSet  =  6

[parFluid]
  fMolMass = 0.0289660
  fGamma   = 1.40
  fVisc    = 0.00001787920
  fKappa   = 0.02529920

[parMesh]
  meshFormat    = 1
  meshFile      = "../../../meshfiles/ringleb4.gmsh"

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 0
  minOrder = 0
  maxOrder = 0
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme     = 3
  timeStepMethod = 1
  timeStep       = 2.4e-2
  cfl            = 5.0e-1

[parOutput]
  ioIter  =  480
  maxIter = 4800
  ioTime  = 0.00
  maxTime = 0.00
  outError = 62

[parRef]
  lengRef  = 1.0
  tempRef  = 288.150
  presRef  = 141855.0
  viscRef  = 1.787920e-5

[parFamilies]
  nFamilies = 5

[parFamilies.1]
  familyName = "MeshInterior"
  familyDimension = 2
  familyType = 0
  familySubType = 62
  familyParameters = []

[parFamilies.2]
  familyName = "Inner"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.3]
  familyName = "Outer"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.4]
  familyName = "Inflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.5]
  familyName = "Outflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

