[parPhysics]
  nDims  =  2
  eqSet  =  6

[parFluid]
  fGamma =    1.4
  fCp    = 1004.5
  fCv    =  717.5
  fR     =  287.0

[parMesh]
  meshFormat    = 1
  meshFile      = "../../../../meshfiles/naca_ref1.gmsh"

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 2
  minOrder = 2
  maxOrder = 2
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme     = 3
  timeStepMethod = 1
  timeStep       = 1.2e-6
  cfl            = 1.0e-1

[parOutput]
  ioIter  = 2000
  maxIter = 200000
  ioTime  = 0.00
  maxTime = 0.00
  outError = 0

[parRef]
  rhoRef  = 1.0
  pRef    = 1.0

[parFamilies]
  nFamilies = 4

[parFamilies.1]
  familyName = "MeshInterior"
  familyDimension = 2
  familyType = 0
  familySubType = 60
  familyParameters = [1.225, 208.303099241307, 7.27410451302232, 271044.375]

[parFamilies.2]
  familyName = "Airfoil"
  familyDimension = 1
  familyType = 4
  familySubType = 42
  familyParameters = []

[parFamilies.3]
  familyName = "Inflow"
  familyDimension = 1
  familyType = 3
  familySubType = 31
  familyParameters = [0.5, 2.0, 0.0, 101325.0, 288.2030861124940]

[parFamilies.4]
  familyName = "Outflow"
  familyDimension = 1
  familyType = 3
  familySubType = 31
  familyParameters = [0.5, 2.0, 0.0, 101325.0, 288.2030861124940]

