[parPhysics]
  nDims  =  2
  eqSet  =  6

[parFluid]
  fGamma =    1.4
  fCp    = 1004.5
  fCv    =  717.5
  fR     =  287.0

[parMesh]
  meshFormat    = 1
  meshFile      = "../../../../meshfiles/naca_ref4.gmsh"

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 5
  minOrder = 0
  maxOrder = 9
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme = 3
  timeStep   = 1.0e-7

[parOutput]
  ioIter  = 5000
  maxIter = 100000
  ioTime  = 0.00
  maxTime = 0.00
  l2ResStop = 1.0e-15
  l2SolStop = 0.0
  outError = 0

[parRef]
  lengRef  = 1.0
  tempRef  = 288.150
  presRef  = 141855.0
  viscRef  = 1.787920e-5

[parFamilies]
  nFamilies = 4

[parFamilies.1]
  familyName = "MeshInterior"
  familyDimension = 2
  familyType = 0
  familySubType = 60
  familyParameters = [1.225, 208.303099241307, 7.27410451302232, 271044.375]

[parFamilies.2]
  familyName = "Airfoil"
  familyDimension = 1
  familyType = 4
  familySubType = 42
  familyParameters = []

[parFamilies.3]
  familyName = "Inflow"
  familyDimension = 1
  familyType = 3
  familySubType = 31
  familyParameters = [0.5, 2.0, 0.0, 101325.0, 288.2030861124940]

[parFamilies.4]
  familyName = "Outflow"
  familyDimension = 1
  familyType = 3
  familySubType = 31
  familyParameters = [0.5, 2.0, 0.0, 101325.0, 288.2030861124940]

