[parPhysics]
  nDims  =  2
  eqSet  =  6

[parFluid]
  fMolMass = 0.0289660
  fGamma   = 1.40
  fVisc    = 0.00001787920
  fKappa   = 0.02529920

[parMesh]
  meshFormat    = 1
  meshFile      = "../../../../meshfiles/naca_ref1-q1.msh"

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 5
  minOrder = 0
  maxOrder = 9
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme = 3
  timeStep   = 0.000003

[parOutput]
  ioIter  =   1111
  maxIter = 333334
  ioTime  = 0.00
  maxTime = 0.00
  l2ResStop = 1.0e-15
  l2SolStop = 0.0
  outError = 0

[parRef]
  lengRef = 1.0
  velMRef = 170.1438138522190
  tempRef = 288.150
  presRef = 141855.0

[parFamilies]
  nFamilies = 4

[parFamilies.1]
  familyName = "MeshInterior"
  familyDimension = 2
  familyType = 0
  familySubType = 60
  familyParameters = [1.225, 208.303099241307, 7.27410451302232, 271044.375]

[parFamilies.2]
  familyName = "Airfoil"
  familyDimension = 1
  familyType = 4
  familySubType = 42
  familyParameters = []

[parFamilies.3]
  familyName = "Inflow"
  familyDimension = 1
  familyType = 3
  familySubType = 31
  familyParameters = [0.5, 2.0, 0.0, 101325.0, 288.2030861124940]

[parFamilies.4]
  familyName = "Outflow"
  familyDimension = 1
  familyType = 3
  familySubType = 31
  familyParameters = [0.5, 2.0, 0.0, 101325.0, 288.2030861124940]

