[parPhysics]
  nDims  =  2
  eqSet  =  6

[parFluid]
  fGamma =    1.4
  fCp    = 1004.5
  fCv    =  717.5
  fR     =  287.0

[parMesh]
  meshFormat    = 1
  meshFile      = "../../../meshfiles/ringleb3.gmsh"

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 1
  minOrder = 1
  maxOrder = 1
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme     = 3
  timeStepMethod = 1
  timeStep       = 0.02
  cfl            = 5.0e-1

[parOutput]
  ioIter  =  1000
  maxIter = 10000
  ioTime  = 0.00
  maxTime = 0.00
  outError = 62

[parRef]
  rhoRef  = 1.0
  pRef    = 1.0

[parFamilies]
  nFamilies = 5

[parFamilies.1]
  familyName = "MeshInterior"
  familyDimension = 2
  familyType = 0
  familySubType = 62
  familyParameters = []

[parFamilies.2]
  familyName = "Inner"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.3]
  familyName = "Outer"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.4]
  familyName = "Inflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.5]
  familyName = "Outflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

