[parPhysics]
  eqSet             = 1

[parConvection]
  convectionSpeed = [1.0, 0.0, 0.0]

[parMesh]
  xMin          =  0.0
  xMax          =  2.0
  nCells        = 20
  meshingScheme = 2

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 2
  minOrder = 0
  maxOrder = 3
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme = 3
  timeStep   = 0.001

[parOutput]
  ioIter  =  100
  maxIter = 1000
  ioTime  = 0.00
  maxTime = 1.00

[parRef]
  rhoRef  = 1.0
  pRef    = 1.0

[parFamilies]
  nFamilies = 3

[parFamilies.1]
  familyName = "flow"
  familyDimension = 1
  familyType = 0
  familySubType = 11
  familyParameters = []

[parFamilies.2]
  familyName = "left"
  familyDimension = 0
  familyType = 9
  familySubType = 92
  familyParameters = [+2.0, 0.0, 0.0]

[parFamilies.3]
  familyName = "right"
  familyDimension = 0
  familyType = 9
  familySubType = 92
  familyParameters = [-2.0, 0.0, 0.0]

