[parPhysics]
  eqSet             = 1
  initialCondition  = 11

[parConvection]
  convectionSpeed = [1.0, 0.0, 0.0]

[parDiffusion]
  diffusionCoef = 1.0

[parFluid]
  fGamma =    1.4
  fCp    = 1004.5
  fCv    =  717.5
  fR     =  287.0

[parMesh]
  xMin          =  0.0
  xMax          =  1.0
  nCells        = 100
  meshingScheme = 1

[parSpatial]
  spatialScheme     = 1
  dissipationScheme = 2

[parFR]
  iOrder   = 3
  minOrder = 2
  maxOrder = 4
  distSP   = 0
  frScheme = 1

[parTime]
  timeScheme = 1
  timeStep   = 0.0001

[parOutput]
  ioIter  = 1
  maxIter = 10
  ioTime  = 0.00
  maxTime = 1.00

[parRef]
  rhoRef  = 10.0
  pRef    = 10.0

[parInit]
  rhoLow  = 1.0
  pLow    = 1.0
  rhoHigh = 10.0
  pHigh   = 10.0
  dummy   = 0

[parFamilies]
  nFamilies = 3

[parFamilies.1]
  familyName = "flow"
  familyDimension = 1
  familyType = 0
  familySubType = 0
  familyParameters = []

[parFamilies.2]
  familyName = "left"
  familyDimension = 0
  familyType = 1
  familySubType = 12
  familyParameters = [1.225, 0.0, 101625.0]

[parFamilies.3]
  familyName = "right"
  familyDimension = 0
  familyType = 2
  familySubType = 22
  familyParameters = [0.97]

