[parPhysics]
  eqSet             = 1
  initialCondition  = 11

[parConvection]
  convectionSpeed = [1.0, 0.0, 0.0]

[parMesh]
  xMin          =  0.0
  xMax          =  2.0
  nCells        = 20
  meshingScheme = 2

[parSpatial]
  spatialScheme     = 1
  dissipationScheme = 2

[parFR]
  iOrder   = 2
  minOrder = 1
  maxOrder = 9
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme = 4
  timeStep   = 0.001

[parOutput]
  ioIter  = 100
  maxIter = 1000
  ioTime  = 0.00
  maxTime = 1.00

[parRef]
  rhoRef  = 10.0
  pRef    = 10.0

[parInit]
  rhoLow  = 1.0
  pLow    = 1.0
  rhoHigh = 10.0
  pHigh   = 10.0
  dummy   = 0

[parFamilies]
  nFamilies = 3

[parFamilies.1]
  familyName = "flow"
  familyDimension = 1
  familyType = 0
  familySubType = 0
  familyParameters = []

[parFamilies.2]
  familyName = "left"
  familyDimension = 0
  familyType = 9
  familySubType = 92
  familyParameters = [+2.0, 0.0, 0.0]

[parFamilies.3]
  familyName = "right"
  familyDimension = 0
  familyType = 9
  familySubType = 92
  familyParameters = [-2.0, 0.0, 0.0]

