[parPhysics]
  eqSet              = 6
  initialConditions  = 1
  boundaryConditions = 0

[parFluid]
  fGamma =    1.4
  fCp    = 1004.5
  fCv    =  717.5
  fR     =  287.0

[parMesh]
  xMin          = -1.0
  xMax          =  1.0
  nCells        = 1000
  meshingScheme = 1

[parSpatial]
  spatialScheme     = 1
  dissipationScheme = 2

[parFR]
  iOrder   = 3
  minOrder = 2
  maxOrder = 4
  distSP   = 0
  frScheme = 1

[parTime]
  timeScheme = 1
  timeStep   = 0.0001

[parOutput]
  ioIter  = 0
  maxIter = 0
  ioTime  = 0.00
  maxTime = 1.00

[parRef]
  rhoRef  = 10.0
  pRef    = 10.0

[parInit]
  rhoLow  = 1.0
  pLow    = 1.0
  rhoHigh = 10.0
  pHigh   = 10.0
  dummy   = 0
