[parPhysics]
  eqSet             = 6

[parConvection]
  convectionSpeed = [1.0, 0.0, 0.0]

[parDiffusion]
  diffusionCoef = 1.0

[parFluid]
  fGamma =    1.4
  fCp    = 1004.5
  fCv    =  717.5
  fR     =  287.0

[parMesh]
  xMin          =  0.0
  xMax          =  1.0
  nCells        = 100
  meshingScheme = 1

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 2
  minOrder = 0
  maxOrder = 3
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme = 3
  timeStep   = 0.001

[parOutput]
  ioIter  =  1000
  maxIter = 10000
  ioTime  = 0.00
  maxTime = 1.00

[parRef]
  rhoRef  = 1.0
  pRef    = 1.0

[parFamilies]
  nFamilies = 3

[parFamilies.1]
  familyName = "flow"
  familyDimension = 1
  familyType = 0
  familySubType = 1
  familyParameters = []

[parFamilies.2]
  familyName = "left"
  familyDimension = 0
  familyType = 1
  familySubType = 12
  familyParameters = [1.225, 0.0, 101625.0]

[parFamilies.3]
  familyName = "right"
  familyDimension = 0
  familyType = 2
  familySubType = 22
  familyParameters = [0.97]

