[parPhysics]
  nDims  =  2
  eqSet  =  6

[parFluid]
  fGamma =    1.4
  fCp    = 1004.5
  fCv    =  717.5
  fR     =  287.0

[parMesh]
  meshFormat    = 1
  meshFile      = "meshfiles/ringleb_sub_half3.gmsh"

[parSpatial]
  spatialScheme     = 11
  dissipationScheme = 0
  limiterScheme     = 0

[parFR]
  iOrder   = 3
  minOrder = 0
  maxOrder = 9
  distSP   = 2
  frScheme = 1

[parTime]
  timeScheme = 3
  timeStep   = 0.01

[parOutput]
  ioIter  = 1000
  maxIter = 100
  ioTime  = 0.00
  maxTime = 1.00
  l2ResStop = 1.0e-15
  l2SolStop = 0.0
  outError = 0

[parRef]
  lengRef  = 1.0
  tempRef  = 288.150
  presRef  = 141855.0
  viscRef  = 1.787920e-5

[parFamilies]
  nFamilies = 5

[parFamilies.1]
  familyName = "MeshInterior"
  familyDimension = 2
  familyType = 0
  familySubType = 62
  familyParameters = []

[parFamilies.2]
  familyName = "Inner"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.3]
  familyName = "Outer"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.4]
  familyName = "Inflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

[parFamilies.5]
  familyName = "Outflow"
  familyDimension = 1
  familyType = 9
  familySubType = 97
  familyParameters = []

